[package]
name = "edda"
version = "0.1.0"
authors = ["Aatu Hieta <aatu@hieta.fi>"]
edition = "2018"

[dependencies]
colored = "1.9.3"
derive-try-from-primitive = "0.1.0"
itertools = "0.9.0"
thiserror = "1.0.20"